### PR TITLE
Set GoodJob dashboard up for super_admins

### PR DESCRIPTION
**Pull request by clarissalimab**
The GoodJob dashboard was configured using the documentation from [this page](https://github.com/bensheldon/good_job#dashboard).

Screenshot from 2021-02-21 10-25-52

The succeeded jobs are not currently showing up on the dashboard, but I suspect this is related to GoodJob configuration itself, not to the dashboard configuration.

### CODE REVIEW

**Comment by wwahammy** [comment]
Succeeding jobs are deleted automatically by default. I think there's instructions on the good_job page to change that as an option.

**Comment by wwahammy** [comment]
@clarissalimab could you add a test to verify super admins can access the dashboard but other users (or non-users) can't?

**Comment by clarissalimab** [comment]
Properly working. It doesn't find the route if the user is not a super admin, and if not logged it redirects to log in screen, is that okay for you?

**Comment by wwahammy** [comment]
I'd like an RSpec test to show that. I want to avoid someone accidentally changing it and not knowing.

**Comment by wwahammy** [comment]
Just for reference, I recommend using a [request](https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec) spec for testing this.

**Comment by wwahammy** [comment]
Here's an example of how to sign in for a test with a given user and role.

https://github.com/houdiniproject/houdini/blob/feature/sign_in-to-mui/spec/controllers/api/nonprofits_controller_spec.rb

**Comment by clarissalimab** [comment]
It is ready for review! :heavy_check_mark:

**Comment by wwahammy** [comment]
We'll just squash and go from there :+1:

**Pull request merged**
